### PR TITLE
Some refreshments

### PR DESCRIPTION
**Pull request by williamdes**
I updated all the crates that did not require a lot of changes

And updated the Docker build
Sadly nobody seems to be using the new crate `actix-ws` and I am not sure to be able to migrate the current implementation

Edit: On my workstation I managed to migrate them and get it to build. Only session init is not wired back. It is quite a pile of mess. That's why it is not pushed.

image

### CODE REVIEW

**Comment by williamdes** [comment]
@JasterV let me know about this PR, I will close it soon as I use another crate now

**Comment by JasterV** [comment]
@williamdes Sorry William, I completely missed this PR in the mess of my github notifications

Thank you so much for contributing!

I will merge it :) 

Also just out of curiosity, have you used this project in a project of yours? How has it helped you?

**Review by JasterV — APPROVED** [review]

**Comment by williamdes** [comment]
> Also just out of curiosity, have you used this project in a project of yours? How has it helped you?

Thank you for merging my work !
What helped was having some bits to implement my own websocket chat room with actix. But actix has some limitations and difficulties. 
Ref: https://github.com/wdes/security/commit/299621ee6fe88780d54ca8331b7d9020ad5586c9 (Move to Actix)
Ref: https://github.com/wdes/security/commit/25df2642e9b62aa54082d55a3ea08358bf29a96c (Move to Rocket)

Clearly Rocket makes it much easier to do multi client chat systems. For my use case I needed a server to send work to workers. Lifetimes where a pain.
And one thing that drove me crazy was that `actix-web-actors` is deprecated, all the existing examples use it.
And there is no way to implement the same logic with the new crate.

Feel free to have a look at my work: https://github.com/wdes/security/commits/main/

And long life to Rocket !

**Comment by JasterV** [comment]
So cool to see Rocket having a comeback!
Rocket was the first web framework I used when getting into Rust, and I loved every single bit of it.
Then Actix gained more popularity and Rocket stopped being maintained for a long time.
Very excited to see thats changing!
Thanks for your comment :)

**Pull request merged**
